env:
    TERM: xterm-256color

window:
    dimensions:
        columns: 133
        lines: 40

    padding:
        x: 6
        y: 6

    title: Alacritty
    
    class:
       instance: Alacritty
       general: Alacritty
    
    opacity: 1

scrolling:
    history: 5000

font:
    normal:
        family: Hack
        style: Regular
    
    bold:
        family: Hack
        style: Bold

    italic:
        family: Hack
        style: Italic

    bold_italic:
        family: Hack
        style: Bold Italic

    size: 11.0

    offset:
        x: 0
        y: 1

draw_bold_text_with_bright_colors: true

key_bindings:
    - { key: V, mods: Control|Shift, action: Paste }
    - { key: C, mods: Control|Shift, action: Copy }
    - { key: PageUp, mods: Shift, action: ScrollPageUp }
    - { key: PageDown, mods: Shift, action: ScrollPageDown }
    - { key: Home, mods: Shift, action: ScrollToTop }
    - { key: End, mods: Shift, action: ScrollToBottom }

shell:
  program: /bin/zsh

